# Generated by Django 5.2.1 on 2025-05-28 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_remove_car_body_type_bodytype_car"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bodytype",
            name="car",
        ),
        migrations.AddField(
            model_name="car",
            name="body_type",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.bodytype",
            ),
            preserve_default=False,
        ),
    ]
