# Generated by Django 5.2.1 on 2025-05-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carmodel",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
