# Generated by Django 5.2.1 on 2025-05-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_carmodel_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="price",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
