# Generated by Django 5.2.1 on 2025-05-28 14:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_user_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocode",
            name="used_by",
            field=models.ManyToManyField(
                blank=True, related_name="used_promo_codes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="CarPark",
        ),
    ]
