# Generated by Django 5.2.1 on 2025-05-28 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_rental"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="body_type",
        ),
        migrations.AddField(
            model_name="bodytype",
            name="car",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.PROTECT, to="main.car"
            ),
        ),
    ]
