# Generated by Django 5.2.1 on 2025-05-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_car_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carmodel",
            name="price",
        ),
        migrations.AlterField(
            model_name="car",
            name="daily_rental_price",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name="car",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
