# Generated by Django 5.2.1 on 2025-05-28 12:49

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_carmodel_price_alter_car_daily_rental_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[main.models.validate_age],
                verbose_name="bd date",
            ),
        ),
    ]
