# Generated by Django 5.2.1 on 2025-05-28 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_promocode_used_by_delete_carpark"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promocode",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="promocode",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="promocode",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="promocode",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="promocode",
            name="used_by",
        ),
        migrations.AddField(
            model_name="promocode",
            name="users",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
