# Generated by Django 5.2.1 on 2025-05-28 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_remove_bodytype_car_car_body_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="body_type",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.bodytype",
            ),
        ),
    ]
