# Generated by Django 5.2.1 on 2025-05-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_car_body_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=10,
                verbose_name="Discount amount",
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="rental_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                max_digits=10,
                verbose_name="Rental amount",
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Waiting confirmation"),
                    ("CONFIRMED", "Confirmed"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                max_digits=10,
                verbose_name="Total amount",
            ),
        ),
    ]
