# Generated by Django 5.2.1 on 2025-05-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_rental_discount_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocode",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
    ]
