# Generated by Django 5.2.5 on 2025-09-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_delete_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
    ]
