# Generated by Django 5.2.5 on 2025-09-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rental_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('about', models.TextField(verbose_name='О компании')),
                ('logo', models.ImageField(blank=True, upload_to='static/info/', verbose_name='Логотип')),
                ('video', models.FileField(blank=True, upload_to='static/info/', verbose_name='Видео')),
                ('history', models.TextField(blank=True, help_text='Пишите историю по годам: 2020 - начали работу, 2022 - открыли новый офис', verbose_name='История компании')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('certificate', models.ImageField(blank=True, upload_to='static/info/', verbose_name='Сертификат')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компания',
            },
        ),
    ]
