# Generated by Django 5.2.8 on 2025-11-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='link',
            field=models.CharField(default='', null=True),
        ),
    ]
