# Generated by Django 5.2.1 on 2025-05-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_remove_promocode_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="name")),
                (
                    "fine",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="fine"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fine",
                "verbose_name_plural": "Fines",
            },
        ),
        migrations.RemoveField(
            model_name="promocode",
            name="users",
        ),
        migrations.RemoveField(
            model_name="user",
            name="discount_points",
        ),
        migrations.AddField(
            model_name="user",
            name="promocodes",
            field=models.ManyToManyField(blank=True, to="main.promocode"),
        ),
        migrations.AddField(
            model_name="user",
            name="fines",
            field=models.ManyToManyField(blank=True, to="main.fine"),
        ),
    ]
