# Generated by Django 5.2.5 on 2025-09-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='website',
            field=models.URLField(verbose_name='website'),
        ),
    ]
