# Generated by Django 5.2.5 on 2025-09-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_partner_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='static/partners', verbose_name='logo'),
        ),
    ]
