# Generated by Django 5.2.5 on 2025-09-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
